services:
  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"
    depends_on:
      stats-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/stats-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "6432:5432"
    environment:
      - POSTGRES_DB=stats-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ewm-service:
    build: main-service
    image: main-service
    container_name: main-service
    ports:
      - "8080:8080"
    depends_on:
      main-db:
        condition: service_healthy
      stats-server:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://main-db:5432/main
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - STATS_SERVER_URL=http://stats-server:9090

  main-db:
    image: postgres:16.1
    container_name: main-db
    ports:
      - "4432:5432"
    environment:
      - POSTGRES_DB=main-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

#----  ----  ----  ----  ---- ----  ----  ----  ----  ----

  user-service:
    build: user-service
    image: user-service
    container_name: user-service
    ports:
      - "8090:8090"
    depends_on:
      user-db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/user-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres

  user-db:
    image: postgres:16.1
    container_name: user-db
    ports:
      - "2232:5432"
    environment:
      - POSTGRES_DB=user-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres