topics:
  userActions: "stats.user-actions.v1"
  eventsSimilarity: "stats.events-similarity.v1"

grpc:
  server:
    port: 0
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext

kafka-aggregator:

  events-similarity-producer:
    properties:
      bootstrap.servers: "localhost:9092"
      group.id: "stats-aggregator-producer-v1"
      key.serializer: "org.apache.kafka.common.serialization.VoidSerializer"
      value.serializer: "ru.practicum.kafka.serializer.GeneralAvroSerializer"

  user-actions-consumer:
    properties:
      bootstrap.servers: "localhost:9092"
      group.id: "stats-aggregator-user-actions-consumers-v1"
      key.deserializer: "org.apache.kafka.common.serialization.VoidDeserializer"
      value.deserializer: "ru.practicum.kafka.serializer.UserActionDeserializer"

      max.poll.records: 100
      fetch.max.bytes: 3072000
      max.partition.fetch.bytes: 307200

      auto.offset.reset: "latest"
      isolation.level: "read_committed"
      enable.auto.commit: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

logging:
  level:
    ru.practicum.ewm.aggregator: DEBUG