spring:

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/analyzer-db
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always

server:
  port: 0

logging:
  level:
    ru.practicum.ewm.analyzer: DEBUG


grpc:
  server:
    port: 0
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext

topics:
  userActions: "stats.user-actions.v1"
  eventsSimilarity: "stats.events-similarity.v1"

kafka-analyzer:

  user-actions-consumer:
    properties:
      bootstrap.servers: "localhost:9092"
      group.id: "stats-analyzer-user-actions-consumers-v1"
      key.deserializer: "org.apache.kafka.common.serialization.VoidDeserializer"
      value.deserializer: "ru.practicum.kafka.serializer.UserActionDeserializer"

      max.poll.records: 100
      fetch.max.bytes: 3072000
      max.partition.fetch.bytes: 307200

      auto.offset.reset: "latest"
      isolation.level: "read_committed"
      enable.auto.commit: false

  events-similarity-consumer:
    properties:
      bootstrap.servers: "localhost:9092"
      group.id: "stats-analyzer-events-similarity-consumers-v1"
      key.deserializer: "org.apache.kafka.common.serialization.VoidDeserializer"
      value.deserializer: "ru.practicum.kafka.serializer.EventsSimilarityDeserializer"

      max.poll.records: 100
      fetch.max.bytes: 3072000
      max.partition.fetch.bytes: 307200

      auto.offset.reset: "latest"
      isolation.level: "read_committed"
      enable.auto.commit: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics

