spring:
  application:
    name: event-service

  datasource:
    url: jdbc:postgresql://localhost:5432/event-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

  sql:
    init:
      mode: always

logging:
  level:
    ru.practicum.ewm: DEBUG

explore-with-me-server:
  url: http://localhost:9090

grpc:
  client:
    analyzer:
      address: 'discovery:///analyzer'
      negotiationType: plaintext
      enableKeepAlive: true
      keepAliveWithoutCalls: true
  collector:
    address: 'discovery:///collector'
    negotiationType: plaintext
    enableKeepAlive: true
    keepAliveWithoutCalls: true

server:
  port: 0